### ISSUE TITLE
How to adapt the algo if we only have 5 bits output instead of 8?

### ISSUE THREAD

**Issue by opnsec** [fx5/not_random#1]
Hi, this is a very nice algo!
I have a scenario where the system discloses only 5 bits of python random.randint:
```
def random_string(length):
    return "".join(chr(random.randint(0, 51)) for i in xrange(length))
```
I tried to modify your algo but I can't make it work. While I understand your solution in general, I don't fully understand how it works in term of solving the system of equations.

My understanding is that:
- The Twister class modelises the system of bitwise equations, in particular the variable twister.tw contains the full MT state in term of bit equations system.
This class is not dependant on the number of bits disclosed so there is no need to modify it.
- I need to modify both gen_magic_data.py and rebuild_random.py to make it work with 4 bits instead of 8 bits known output.

I modified  gen_magic_data.py like this for 4 bits:

```
# gen_magic_data.py
#...
def iter_bits_4_bit(twister):
        #...
        #for bit in int32[:8]: ***REPLACED BY:***
        for bit in int32[:4]:
            yield bit
#...
    def _verify(rule, force=False):
        #...
        #b1 = 1 & sum((verify_data[x // 8] >> (7 - x % 8)) & 1 ***REPLACED BY:***
        b1 = 1 & sum((verify_data[x // 4] >> (3 - x % 4)) & 1
                     for x in bitfield1.itersearch(bitarray([1])))
#...
def main():
    """Main function"""
    #bits1 = 3500 * 8 ***REPLACED BY:***
    bits1 = 20000 * 4 # *** I tried multiple value instead of 20000, it seems if high enough it doesn't change the magic_data file
    #...
    rng_data = [rnd.randint(0, 255) for _ in xrange(bits1/8)] ***REPLACED BY:***
    rng_data = [rnd.randint(0, 15) for _ in xrange(bits1/4)]
```
There is no error and the magic_data file generated is twice as large as the one with 8 bits

```
# rebuild_random.py
#...
def rebuild_random(magic, data):
        #...
        xor_data = reduce(lambda a, b: a ^ b,
                          #(xor_data >> i for i in xrange(8))) ***REPLACED BY:***
                          (xor_data >> i for i in xrange(4)))
#...
def random_string(length, random_obj=random):
    #...
    #return "".join(chr(random_obj.randint(0, 255)) for _ in xrange(length)) ***REPLACED BY:***
    return "".join(chr(random_obj.randint(0, 15)) for _ in xrange(length))
#...
def main():
    #...
    need_bytes = max(len(d) for d in magic)

    # First we receive 3115 bytes from our random-function
    first_random_string = random_string(need_bytes) ***TRIED WITH need_bytes*2 or need_bytes*10 ***
#...

```
The first problem in rebuild_random.py is that with 8 bits, need_bytes is 3115, as you explained in the README. 
But with 4 bits, need_bytes is 2493 which doesn't make sense since with 4bits we should need at least 19968 / 4 = 4992 bits of outpout to recover the full 19968 bits MT state

I also tried to manually set need_bytes to a higher value but it didn't work.

At the end the state recovery always fails. I also tried the same modifications for 16 bits output but I have the same problems (need_bytes is high than it should be and the state recovery fails)

Can you help me resolve this? I hope this is clear and I can provide more details.
I guess I either missed a few variables to change, or I changed a variable that I shouldn't have changed?
Or maybe your magic_data generator is only meant to work with 8 bits outpout and I need to create a different adhoc algo for 4 bits? In that case, does this algo follows a particular mathematical algo that have a name?

Thanks!

**Comment by fx5** [comment]
Enguerran,

sorry that I didn't do much research for answering the question.

I believe your changes to the gen_magic_data.py look good and you probably created the correct data.

I believe need_bytes * 8 is the number of observed bits you need from the mersenne twister. In your case that means you need ceil(need_bytes * 8 / 5) observed outputs from random.randint(0, 51). You have to isolate the 5 mt-output-bits from random.randint(0, 51) and concatenate that bits to a byte-string of length need_bytes.

After recovering the mt-state, you can use the state to produce the complete random.randint(0, 51) output, but to recover the state, you need to work with the 5 bits you can recover from [0...51] (transform [0...51] to [0...31]) only.

If you manage to make the code more generic, a PR would be highly welcome.

**Comment by opnsec** [comment]
Thanks! 
`ceil(need_bytes * 8 / 5)` (or more generically `ceil(need_bytes * 8 / x)`) produce values that makes sense (the least output bits you have, the more bits you need).
I understand about extracting of [0...31] (5 bits) and concacatenates to a byte-string of length need_bytes, but I must have missed something because the state recovery fails at the end. 

I'm wondering maybe the .tobytes() method of the serialization of magic_data needs some adjustment for bitarrays not of length 8.

If I can make it work I'll be happy to PR!

**Comment by opnsec** [comment]
I managed to make it work for output bits of length 1 to 8. In addition to the changes I mentionned, I had to add masking "0" to the bitarray in gen_magic_data.py/save_data() before calling bitarray.tobytes().
I'll send a PR!

BTW I managed to predict the output of random.randint(0, 51) using it. Interestingly, the range has a length of 52, but it doesn't reveal exactly 5 bits output of the MT PRNG, but only 2 bits. In general, to know how much bits output a range reveals, you can count the number of trailing "0" of the range size in binary (52 has 2 trailing "0" for example, which means 52 is divisible by 2**2).
